baseURL = "https://domingosleao.github.io/"
languageCode = "pt-br"
paginate = 6
theme = "portio"
title = "Armazém Soluções Empresariais"
publishDir = "docs"
# Main Menu
[[menu.main]]
name = "Início"
url = "#home"
weight = 1
[[menu.main]]
name = "Sobre"
url = "#about"
weight = 2
[[menu.main]]
name = "Nossos serviços"
url = "#service"
weight = 3
[[menu.main]]
name = "Princípios Organizacionais"
url = "#resume"
weight = 4

# Sitemap Menu
[[menu.sitemap]]
name = "Sobre a empresa"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Entre em contato"
url = "contact"
weight = 2


[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = ""
footerLogo = "images/contact/widget-logo.png"
formspreeURL = "https://formspree.io/f/xnqglobv"
googleAnalytics = "G-RKY0QK9FFC"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Av. Fernandes Lima, 8, sala 406, cx post H21 - Edf. Com. Centenário Plaza - Farol - Maceió - AL CEP 57050-000"
email = "contato@domingosleao.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(55) 82 993055821"

[params.map]
APIkey = ""
latitude = "-9.650010"
longitude = "-35.733300"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/domingos-le%C3%A3o-34b91921/"
weight = 1
[[params.social]]
icon = "fa-facebook-square"
url = "https://www.facebook.com/leaodomingos/"
weight = 2
[[params.social]]
icon = "fa-youtube-square"
url = "https://www.youtube.com/user/leaodomingos"
weight = 3
[[params.social]]
icon = "fa-instagram-square"
url = "https://www.instagram.com/domingosleao/"
weight = 4
